apiVersion: apps/v1
kind: Deployment
metadata:
  name: clsi
  namespace: default
spec:
  selector:
    matchLabels:
      app: clsi
  template:
    metadata:
      labels:
        app: clsi    
    spec:
      containers:
        - name: clsi
          image: image1
          imagePullPolicy: Always
          command:
          - 'clsi'
          ports:
          - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /livez
              port: 3001
            initialDelaySeconds: 5
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: clsi
  namespace: default
spec:
  ports:
  - port: 3001
    protocol: TCP
    targetPort: 8080
  selector:
    app: clsi
  type: ClusterIP
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: clsi
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: clsi
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80
---
apiVersion: monitoring.googleapis.com/v1
kind: PodMonitoring
metadata:
  name: clsi
spec:
  selector:
    matchLabels:
      app: clsi
  endpoints:
  - port: 8080
    interval: 30s
